channels:
- conda-forge
- nvidia
- pytorch
- anaconda
dependencies:
- python=3.9.22
- pip:
  - adal==1.2.7
  - annotated-types==0.7.0
  - applicationinsights==0.11.10
  - arch==5.6.0
  - argcomplete==3.6.2
  - asttokens==3.0.0
  - attrs==25.3.0
  - azure-common==1.1.28
  - azure-core==1.33.0
  - azure-graphrbac==0.61.2
  - azure-identity==1.21.0
  - azure-mgmt-authorization==4.0.0
  - azure-mgmt-containerregistry==10.3.0
  - azure-mgmt-core==1.5.0
  - azure-mgmt-keyvault==10.3.1
  - azure-mgmt-network==28.1.0
  - azure-mgmt-resource==23.3.0
  - azure-mgmt-storage==22.1.1
  - azure-storage-blob==12.19.0
  - azure-storage-queue==12.12.0
  - azureml-automl-core==1.60.0
  - azureml-automl-runtime==1.60.0
  - azureml-core==1.60.0
  - azureml-dataprep==5.1.6
  - azureml-dataprep-native==41.0.0
  - azureml-dataprep-rslex==2.22.5
  - azureml-dataset-runtime==1.60.0
  - azureml-defaults==1.60.0
  - azureml-inference-server-http==1.4.0
  - azureml-interpret==1.60.0
  - azureml-mlflow==1.60.0
  - azureml-pipeline-core==1.60.0
  - azureml-responsibleai==1.60.0
  - azureml-telemetry==1.60.0
  - azureml-train-automl==1.60.0
  - azureml-train-automl-client==1.60.0
  - azureml-train-automl-runtime==1.60.0
  - azureml-train-core==1.60.0
  - azureml-train-restclients-hyperdrive==1.60.0
  - azureml-training-tabular==1.60.0
  - backports-tempfile==1.0
  - backports-weakref==1.0.post1
  - bcrypt==4.3.0
  - blinker==1.9.0
  - bokeh==2.4.3
  - cachetools==5.5.2
  - certifi==2025.1.31
  - cffi==1.17.1
  - charset-normalizer==3.4.1
  - cmdstanpy==1.2.5
  - coloredlogs==15.0.1
  - comm==0.2.2
  - contextlib2==21.6.0
  - contourpy==1.3.0
  - convertdate==2.4.0
  - cryptography==44.0.2
  - cycler==0.12.1
  - cython==3.0.12
  - dask==2023.2.0
  - databricks-sdk==0.50.0
  - dataclasses==0.6
  - debugpy==1.8.14
  - decorator==5.2.1
  - deprecated==1.2.18
  - dice-ml==0.11
  - dill==0.3.9
  - distributed==2023.2.0
  - distro==1.9.0
  - docker==7.1.0
  - dotnetcore2==3.1.23
  - econml==0.15.1
  - entrypoints==0.4
  - ephem==4.2
  - erroranalysis==0.5.5
  - exceptiongroup==1.2.2
  - executing==2.2.0
  - fairlearn==0.7.0
  - fire==0.7.0
  - flask==3.0.3
  - flask-cors==5.0.1
  - flatbuffers==25.2.10
  - fonttools==4.57.0
  - fsspec==2025.3.2
  - fusepy==3.0.1
  - gensim==4.3.2
  - gitdb==4.0.12
  - gitpython==3.1.44
  - google-api-core==2.24.2
  - google-auth==2.38.0
  - googleapis-common-protos==1.70.0
  - gunicorn==23.0.0
  - humanfriendly==10.0
  - idna==3.10
  - importlib-metadata==7.2.1
  - importlib-resources==6.4.0
  - inference-schema==1.8
  - interpret-community==0.31.0
  - interpret-core==0.5.0
  - ipykernel==6.29.5
  - ipython==8.18.1
  - isodate==0.7.2
  - itsdangerous==2.2.0
  - jedi==0.19.2
  - jeepney==0.9.0
  - jmespath==0.10.0
  - jsonpickle==4.0.5
  - jsonschema==4.23.0
  - jsonschema-specifications==2024.10.1
  - jupyter-client==8.6.3
  - jupyter-core==5.7.2
  - keras2onnx==1.6.0
  - kiwisolver==1.4.7
  - knack==0.12.0
  - lightgbm==4.6.0
  - locket==1.0.0
  - lunarcalendar==0.0.9
  - matplotlib==3.9.4
  - matplotlib-inline==0.1.7
  - ml-wrappers==0.5.6
  - mlflow-skinny==2.15.1
  - mltable==1.6.1
  - msal==1.32.0
  - msal-extensions==1.3.1
  - msgpack==1.1.0
  - msrest==0.7.1
  - msrestazure==0.6.4.post1
  - ndg-httpsclient==0.5.1
  - nest-asyncio==1.6.0
  - networkx==2.5
  - numba==0.56.4
  - oauthlib==3.2.2
  - onnx==1.17.0
  - onnxconverter-common==1.13.0
  - onnxmltools==1.12.0
  - onnxruntime==1.17.3
  - opencensus==0.11.4
  - opencensus-context==0.1.3
  - opencensus-ext-azure==1.1.14
  - opentelemetry-api==1.32.0
  - opentelemetry-sdk==1.32.0
  - opentelemetry-semantic-conventions==0.53b0
  - packaging==24.2
  - paramiko==3.5.1
  - parso==0.8.4
  - partd==1.4.2
  - pathspec==0.12.1
  - patsy==1.0.1
  - pexpect==4.9.0
  - pillow==11.2.1
  - pkginfo==1.12.1.2
  - platformdirs==4.3.7
  - pmdarima==1.8.5
  - prompt-toolkit==3.0.50
  - property-cached==1.6.4
  - prophet==1.1.4
  - proto-plus==1.26.1
  - protobuf==5.29.4
  - ptyprocess==0.7.0
  - pure-eval==0.2.3
  - pyarrow==14.0.2
  - pyasn1==0.6.1
  - pyasn1-modules==0.4.2
  - pycparser==2.22
  - pydantic==2.9.2
  - pydantic-core==2.23.4
  - pydantic-settings==2.8.1
  - pygments==2.19.1
  - pyjwt==2.10.1
  - pymeeus==0.5.12
  - pynacl==1.5.0
  - pyopenssl==25.0.0
  - pyparsing==3.2.3
  - pysocks==1.7.1
  - python-dateutil==2.9.0.post0
  - python-dotenv==1.1.0
  - pytz==2024.2
  - pyzmq==26.4.0
  - raiutils==0.4.2
  - referencing==0.36.2
  - requests==2.32.3
  - requests-oauthlib==2.0.0
  - responsibleai==0.36.0
  - rpds-py==0.24.0
  - rsa==4.9
  - s3transfer==0.5.2
  - scipy==1.10.1
  - secretstorage==3.3.3
  - semver==2.13.0
  - six==1.17.0
  - skl2onnx==1.15.0
  - sklearn-pandas==1.7.0
  - slicer==0.0.7
  - smart-open==6.4.0
  - smmap==5.0.2
  - sortedcontainers==2.4.0
  - sparse==0.15.5
  - sqlparse==0.5.3
  - stack-data==0.6.3
  - stanio==0.5.1
  - statsmodels==0.13.5
  - tabulate==0.9.0
  - tblib==3.1.0
  - termcolor==3.0.1
  - threadpoolctl==3.6.0
  - toolz==1.0.0
  - tornado==6.4.2
  - tqdm==4.67.1
  - traitlets==5.14.3
  - urllib3==1.26.20
  - wcwidth==0.2.13
  - werkzeug==3.1.3
  - wrapt==1.16.0
  - xgboost==1.5.2
  - zict==3.0.0
  - zipp==3.21.0
- blas-devel=3.9.0
- boto3=1.20.19
- botocore=1.23.19
- bzip2=1.0.8
- ca-certificates=2025.1.31
- cloudpickle=2.2.1
- cpython=3.9.22
- cuda-cudart=12.1.105
- cuda-cudart_linux-64=12.1.105
- cuda-cupti=12.1.105
- cuda-libraries=12.1.0
- cuda-nvrtc=12.1.105
- cuda-nvtx=12.1.105
- cuda-opencl=12.1.105
- cuda-runtime=12.1.0
- cuda-version=12.1
- filelock=3.18.0
- gmp=6.3.0
- gmpy2=2.1.5
- holidays=0.70
- jinja2=3.1.6
- joblib=1.2.0
- libcublas=12.1.0.26
- libcufft=11.0.2.4
- libcufile=1.6.1.9
- libcurand=10.3.2.106
- libcusolver=11.4.4.55
- libcusparse=12.0.2.55
- libffi=3.4.6
- libgcc=14.2.0
- libgfortran=14.2.0
- libgfortran-ng=14.2.0
- libgfortran5=14.2.0
- libhwloc=2.11.2
- libiconv=1.18
- liblzma=5.8.1
- libnpp=12.0.2.50
- libnsl=2.0.1
- libnvjitlink=12.1.105
- libnvjpeg=12.1.1.14
- libsqlite=3.49.1
- libstdcxx=14.2.0
- libuuid=2.38.1
- libxcrypt=4.4.36
- libxml2=2.13.7
- libzlib=1.3.1
- llvm-openmp=15.0.7
- llvmlite=0.39.1
- markupsafe=3.0.2
- mkl=2022.1.0
- mkl-devel=2022.1.0
- mkl-include=2022.1.0
- mpc=1.3.1
- mpfr=4.2.1
- mpmath=1.3.0
- numpy=1.23.5
- ocl-icd=2.3.3
- opencl-headers=2024.10.24
- pandas=1.5.3
- pip=25.0.1
- psutil=5.9.3
- py-cpuinfo=5.0.0
- python_abi=3.9
- pytorch=2.2.2
- pytorch-cuda=12.1
- pytorch-mutex=1.0
- pyyaml=6.0.2
- scikit-learn=1.5.1
- setuptools=78.1.0
- setuptools-git=1.2
- sympy=1.13.3
- tbb=2021.13.0
- torchtriton=2.2.0
- typing_extensions=4.13.2
- tzdata=2025b
- wheel=0.45.1
- yaml=0.2.5
name: project_environment
